### ISSUE TITLE
Push libretro core upstream

### ISSUE THREAD

**Issue by RobLoach** [libretro/easyrpg-libretro#11]
@Ghabry mentioned he'd be willing to bring the libretro core changes upstream into [EasyRPG Player](https://github.com/EasyRPG/Player). cc @ChristianBreitwieser

## TODO

- [ ] Handle `lib` directory
- [ ] Clean up libretro changes
- [ ] Bring changes over to EasyRPG
- [ ] Anything else?

**Comment by Ghabry** [comment]
Imo the best way to start working on this is to create a new branch here in the repo which is based on "upstream/master" and to cherry-pick all libretro-related commits that are unrelated with libs. Pushing the builds/retro/Makefile upstream is fine I guess because it's very small.

Style:
- Make sure that all additions by libretro to the easyrpg source matches the code style (e.g. Tabs instead of spaces). decoder_wildmidi.cpp is one example of this. Same for audio_libretro.cpp which has a totally inconsistent idendation.
- Remove commits that have no effect anymore, e.g. "lets not pass -700 this just crashes" or "fix derped allocations" because this was already fixed upstream. The "simplify endian-ness functions" code changes is also not used anymore since the 0.5.2 update
- Some commits could be squashed into one. E.g. everything related to audio_libretro2. Is 10 commits which are mostly only one line changes.

Code:
- image_xyz.cpp: Why was the signature of the zlib function uncompress changed?
- The destructor of audio libretro does not free resources (the mutex)
- How does libretro handle keys? By looking at libretro_ui I only see direction, action and cancel. EasyRPG has much more keys. See https://github.com/libretro/easyrpg-libretro/blob/master/src/input_buttons.h#L30 (ask if the purpose of a key is not clear)

To discuss:
- You added !USE\_LIBRETRO after some \_\_ANDROID\_\_ conditionals because we assume that when building for Android SDL is available. I guess similiar conflicts will be when building for Wii (GEKKO) and other platforms. When EMSCRIPTEN is defined the Player behaves totally different, too when accessing files. How can we solve these conflicts?

**Comment by Ghabry** [comment]
Closing this because I opened an upstream pull request.
Doesn't solve the library dependency problem but this is nothing upstream should be supposed to handle (except for libretro-common).

https://github.com/EasyRPG/Player/pull/1464
